# Generated by Django 3.2.17 on 2023-02-14 21:18

import Profile.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=11, null=True)),
                ('refferal', models.CharField(blank=True, max_length=7, null=True)),
                ('user_code', models.CharField(default=Profile.models.generate_unique_code, max_length=7, unique=True)),
                ('profile_pic', models.ImageField(blank=True, default='', null=True, upload_to='media/user_profile_images/')),
                ('total_earned', models.CharField(blank=True, default='0', max_length=5000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
