# Generated by Django 3.2.17 on 2023-02-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='user_profile_images/'),
        ),
    ]
