# Generated by Django 3.2.18 on 2023-05-06 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_profile_recentearnings_referral_resetpassword_socialaccount_transaction_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic_path',
            field=models.CharField(blank=True, default='https://i.ibb.co/MCCTf9R/profile-image-2.png', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='signed_up_at',
            field=models.DateField(default=datetime.date(2023, 5, 6)),
        ),
    ]
