# Generated by Django 3.2.17 on 2023-02-14 21:51

import Profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic_path',
            field=models.CharField(blank=True, default=Profile.models.get_random_image_path, max_length=255, null=True),
        ),
    ]
