# Generated by Django 3.2.17 on 2023-02-18 19:37

import Profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_code',
            field=models.CharField(blank=True, default=Profile.models.generate_unique_code, max_length=7, null=True, unique=True),
        ),
    ]
