# Generated by Django 3.2.18 on 2023-05-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_auto_20230519_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.CharField(default='01-05-2023', max_length=50),
        ),
    ]
