# Generated by Django 3.2.17 on 2023-02-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_auto_20230222_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='refferal',
        ),
    ]
