# Generated by Django 3.2.18 on 2023-05-24 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0010_auto_20230520_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentearnings',
            name='created_at',
            field=models.DateField(default=datetime.date(2023, 5, 24)),
        ),
        migrations.AlterField(
            model_name='referral',
            name='signed_up_at',
            field=models.DateField(default=datetime.date(2023, 5, 24)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateField(default=datetime.date(2023, 5, 24)),
        ),
    ]
