# Generated by Django 3.2.17 on 2023-02-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_auto_20230223_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(default='Easypaisa', max_length=100),
        ),
    ]
