# Generated by Django 3.2.18 on 2023-06-06 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0012_auto_20230528_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_earned',
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.CharField(default='Click Here To Add', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.CharField(blank=True, default='Click Here To Add', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='recentearnings',
            name='created_at',
            field=models.DateField(default=datetime.date(2023, 6, 6)),
        ),
        migrations.AlterField(
            model_name='referral',
            name='signed_up_at',
            field=models.DateField(default=datetime.date(2023, 6, 6)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateField(default=datetime.date(2023, 6, 6)),
        ),
    ]
