# Generated by Django 3.2.17 on 2023-02-23 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0012_alter_transaction_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentearnings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.profile'),
        ),
    ]
