# Generated by Django 3.2.18 on 2023-06-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0013_auto_20230606_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.CharField(blank=True, default='Click Here To Add', max_length=500, null=True),
        ),
    ]
