# Generated by Django 3.2.17 on 2023-02-23 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0016_alter_recentearnings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Profile.profile'),
        ),
    ]
