# Generated by Django 3.2.18 on 2023-04-02 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0017_alter_referral_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentearnings',
            options={'ordering': ['-entry_number']},
        ),
        migrations.AddField(
            model_name='recentearnings',
            name='entry_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recentearnings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
