# Generated by Django 3.2.18 on 2023-04-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0018_auto_20230402_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentearnings',
            options={},
        ),
        migrations.RemoveField(
            model_name='recentearnings',
            name='entry_number',
        ),
    ]
