# Generated by Django 3.2.18 on 2023-04-04 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0019_auto_20230402_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='signed_up',
            field=models.DateField(default=datetime.date(2023, 4, 4)),
        ),
    ]
