# Generated by Django 3.2.18 on 2023-04-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0020_referral_signed_up'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='signed_up',
            new_name='signed_up_at',
        ),
    ]
