# Generated by Django 3.2.18 on 2023-04-08 16:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0022_auto_20230408_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='signed_up_at',
            field=models.DateField(default=datetime.date(2023, 4, 8)),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 16, 40, 9, 417431, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
