# Generated by Django 3.2.18 on 2023-04-10 23:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0023_auto_20230408_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resetpassword',
            name='code',
        ),
        migrations.AddField(
            model_name='resetpassword',
            name='pin',
            field=models.CharField(default=1, max_length=4),
        ),
        migrations.AlterField(
            model_name='referral',
            name='signed_up_at',
            field=models.DateField(default=datetime.date(2023, 4, 10)),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 23, 32, 32, 721663, tzinfo=utc)),
        ),
    ]
