# Generated by Django 3.2.18 on 2023-04-11 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0024_auto_20230411_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='signed_up_at',
            field=models.DateField(default=datetime.date(2023, 4, 11)),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
