# Generated by Django 3.2.18 on 2023-04-20 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0026_alter_referral_signed_up_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='signed_up_at',
            field=models.DateField(default=datetime.date(2023, 4, 20)),
        ),
    ]
