# Generated by Django 3.2.18 on 2023-06-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_questions_quiz_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monsterhunter',
            name='turn_available',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='ticktactoe',
            name='turn_available',
            field=models.IntegerField(default=10),
        ),
    ]
