# Generated by Django 3.2.18 on 2023-04-12 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_auto_20230412_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinwheel',
            name='last_played_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 12, 20, 33, 21, 290898), null=True),
        ),
    ]
