# Generated by Django 3.2.18 on 2023-04-12 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_alter_spinwheel_last_played_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monsterhunter',
            name='last_played_at',
        ),
        migrations.RemoveField(
            model_name='spinwheel',
            name='last_played_at',
        ),
        migrations.RemoveField(
            model_name='ticktactoe',
            name='last_played_at',
        ),
    ]
