# Generated by Django 3.2.18 on 2023-04-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0005_auto_20230412_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monsterhunter',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='spinwheel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ticktactoe',
            name='created_at',
        ),
        migrations.AddField(
            model_name='monsterhunter',
            name='last_played_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='spinwheel',
            name='last_played_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticktactoe',
            name='last_played_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
