# Generated by Django 3.2.18 on 2023-04-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0006_auto_20230412_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinwheel',
            name='last_played_at',
            field=models.DateTimeField(),
        ),
    ]
