# Generated by Django 3.2.18 on 2023-07-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0007_videos_zolovideos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='videos',
            field=models.TextField(),
        ),
    ]
