# Generated by Django 3.2.18 on 2023-07-16 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0008_alter_videos_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zolovideos',
            name='videos_watched',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
