# Generated by Django 3.2.18 on 2023-07-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0011_alter_articles_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='title',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
